chains:
  - chain_id: 1

    # View-only private key (0zk)
    viewing_privkey: 0x82a57...

    # Private keys for EVM transaction senders. Hex format.
    evm_wallets:
      - 0xabcd1234...

    # Fee bonus in %
    fee_bonus: 5

    # How long posted fees will be valid for
    fees_ttl: 5m

    # How often to refresh/publish fees
    fees_refresh_interval: 30s

    # Optional identifier for this broadcaster. Wallets may or may not display it.
    identifier: rust-broadcaster

    # RPC endpoint for querying the chain
    query_rpc: https://eth.llamarpc.com

    # List of tokens to accept fees in. Price should be expressed in tokens per Wei.
    # Chainlink oracles are supported. Oracle must return ETH/TOKEN price. If it returns TOKEN/ETH then `is_inversed` must be set to true.
    fees:
      # WETH
      0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2: !Fixed 1000000000000000000
      # USDT
      0xdAC17F958D2ee523a2206206994597C13D831ec7: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 6
      # USDC
      0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 6
      # DAI
      0x6b175474e89094c44da98b954eedeac495271d0f: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 18
      # WBTC
      0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599: !Oracle
        addr: 0xdeb288F737066589598e9214E782fa5A8eD689e8
        is_inversed: true
        token_decimals: 8

    # List of RPC endpoints to submit transactions to.
    # Rpc types supported:
    # - Normal - regular JSON-RPC endpoint
    # - Private - JSON-RPC endpoint that doesn't broadcast to mempool (i.e. Flashbots Protect: see https://docs.flashbots.net/flashbots-protect/overview)
    # - Flashbots - Flashbots relay endpoint (See https://docs.flashbots.net/flashbots-auction/quick-start for more details)
    # - BloxrouteBackrunme - Bloxroute Backrunme relay endpoint, requires API key. See https://docs.bloxroute.com/bsc-and-eth/apis/frontrunning-protection
    # Transactions without action_data will be sent to mempool (Normal RPCs).
    # Transactions with action_data (potential Private Swap payload) will be submitted to Private,
    #   Flashbots and BloxrouteBackrunme in order to protect users from sandwich attacks and potentially
    #   earn a portion of profit from backrunning MEV.
    submit_rpcs:
      - !Normal https://eth.llamarpc.com
      - !Private
        url: https://rpc.flashbots.net/fast
        has_mev: true
      - !Flashbots
        url: https://relay.flashbots.net
        num_blocks: 10
      #- !BloxrouteBackrunme
      #  url: https://api.blxrbdn.com
      #  api_key: <FILL_ME>

    # Advanced configuration
    relay_adapt_contract: 0xAc9f360Ae85469B27aEDdEaFC579Ef2d052aD405
    multicall_contract: 0xcA11bde05977b3631167028862bE2a173976CA11

waku:
  # URL to a dedicated nwaku relay (optional)
  #nwaku_url: <FILL_ME>

  # Waku cluster id
  cluster_id: 1

  # List of custom DNS-based enr trees to bootstrap the libp2p network.
  #  Leave commented out to use default bootstrap nodes.
  #  Use empty list to disable DNS bootstrap.
  #dns_enr_trees: []

  # DNS-over-HTTPS endpoint to use for DNS resolution.
  doh_endpoint: "https://cloudflare-dns.com/dns-query"

  # Maximum number of peers to maintain persistent connections with
  max_peers: 10

  # Timeout for establishing a peer connection
  peer_connection_timeout: "10s"

  # List of direct peers to connect to. More peers may be discovered through Peer Exchange protocol.
  direct_peers:
    - peer_id: "16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m"
      addrs: [ "/dns4/prod.rootedinprivacy.com/tcp/30304/p2p/16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m", "/dns4/prod.rootedinprivacy.com/tcp/8000/wss/p2p/16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m" ]

poi_rpc: https://ppoi.fdi.network
required_poi_list:
  # Chainalysis OFAC Sanctions API
  - efc6ddb59c098a13fb2b618fdae94c1c3a807abc8fb1837c93620c9143ee9e88
