chains:
  # Ethereum
  - chain_id: 1

    # View-only private key (0zk)
    # key: !ViewingPrivkey 0x82a57...

    # or mnemonic seed phrase
    key: !Mnemonic
      seed_phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
      # The starting block number from which to search for unspent UTXOs
      init_block_number: 24370000
      # Number of EVM wallets to derive from the seed to use as senders (m/44'/60'/0'/0/{index})
      num_derived_evm_wallets: 0
      # Auto-refill EVM wallets by unshielding WETH and unwrapping to ETH when their balance falls below `min_amount`.
      auto_refill:
        # How often to check wallet balances
        interval: 10m
        # Skip refill if gas price is too high
        max_gas_price: 0.5gwei
        # Trigger refill when balance drops below this
        min_amount: 0.1ether
        # Amount to refill up to
        target_amount: 0.2ether

      # Consolidate UTXOs into larger notes when gas is cheap
      utxo_consolidation:
        # How often to check for consolidations
        interval: 30m
        # Skip consolidation if gas price is too high
        max_gas_price: 0.5gwei
        # Minimum number of UTXOs in a tree to start consolidation
        min_utxos: 20
        # Tokens eligible for consolidation
        tokens:
          - 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
          - 0xdAC17F958D2ee523a2206206994597C13D831ec7
          - 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
          - 0x6b175474e89094c44da98b954eedeac495271d0f
          - 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599

    # Private keys for EVM transaction senders. Hex format.
    # Can be empty if `key` is set to Mnemonic and `num_derived_evm_wallets` is non-zero.
    evm_wallets:
      - 0xabcd1234...

    # Fee bonus in %
    fee_bonus: 5

    # How long posted fees will be valid for
    fees_ttl: 5m

    # How often to refresh/publish fees
    fees_refresh_interval: 30s

    # Optional identifier for this broadcaster. Wallets may or may not display it.
    identifier: rust-broadcaster

    # RPC endpoints for querying the chain
    query_rpcs:
      - https://eth.llamarpc.com
      - https://ethereum-rpc.publicnode.com
      - https://ethereum-public.nodies.app
      - https://eth-mainnet.g.alchemy.com/v2/demo

    # List of tokens to accept fees in. Price should be expressed in tokens per Wei.
    # Chainlink oracles are supported. Oracle must return ETH/TOKEN price. If it returns TOKEN/ETH then `is_inversed` must be set to true.
    fees:
      # WETH
      0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2: !Fixed "1ether"
      # USDT
      0xdAC17F958D2ee523a2206206994597C13D831ec7: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 6
      # USDC
      0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 6
      # DAI
      0x6b175474e89094c44da98b954eedeac495271d0f: !Oracle
        addr: 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
        token_decimals: 18
      # WBTC
      0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599: !Oracle
        addr: 0xdeb288F737066589598e9214E782fa5A8eD689e8
        is_inversed: true
        token_decimals: 8

    # List of RPC endpoints to submit transactions to.
    # Rpc types supported:
    # - Normal - regular JSON-RPC endpoint
    # - Private - JSON-RPC endpoint that doesn't broadcast to mempool (i.e. Flashbots Protect: see https://docs.flashbots.net/flashbots-protect/overview)
    # - Flashbots - Flashbots relay endpoint (See https://docs.flashbots.net/flashbots-auction/quick-start for more details)
    # - BloxrouteBackrunme - Bloxroute Backrunme relay endpoint, requires API key. See https://docs.bloxroute.com/bsc-and-eth/apis/frontrunning-protection
    # Transactions without action_data will be sent to mempool (Normal RPCs).
    # Transactions with action_data (potential Private Swap payload) will be submitted to Private,
    #   Flashbots and BloxrouteBackrunme in order to protect users from sandwich attacks and potentially
    #   earn a portion of profit from backrunning MEV.
    submit_rpcs:
      - !Normal https://eth.llamarpc.com
      - !Private
        url: https://rpc.flashbots.net/fast
        has_mev: true
      - !Flashbots
        url: https://relay.flashbots.net
        num_blocks: 10
      #- !BloxrouteBackrunme
      #  url: https://api.blxrbdn.com
      #  api_key: <FILL_ME>

    # Advanced configuration
    wrapped_native_token: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
    railgun_contract: 0xfa7093cdd9ee6932b4eb2c9e1cde7ce00b1fa4b9
    relay_adapt_contract: 0xAc9f360Ae85469B27aEDdEaFC579Ef2d052aD405
    multicall_contract: 0xcA11bde05977b3631167028862bE2a173976CA11

  # BSC
  - chain_id: 56
    viewing_privkey: 0x82a57...
    evm_wallets:
      - 0xabcd1234...
    fee_bonus: 25
    fees_ttl: 5m
    fees_refresh_interval: 30s
    identifier: rust-broadcaster
    query_rpcs:
      - https://binance-smart-chain-public.nodies.app
      - https://rpc-bsc.48.club
      - https://binance.nodereal.io
      - https://bsc-rpc.publicnode.com
      - https://bsc-mainnet.public.blastapi.io
      - https://api.zan.top/bsc-mainnet
      - https://public-bsc.nownodes.io
      - https://rpc.sentio.xyz/bsc
    fees:
      # BNB
      0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c: !Fixed "1ether"
      # BSC-USD
      0x55d398326f99059ff775485246999027b3197955: !Oracle
        addr: 0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE
        token_decimals: 18
      # USDC
      0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d: !Oracle
        addr: 0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE
        token_decimals: 18
      # BUSD
      0xe9e7cea3dedca5984780bafc599bd69add087d56: !Oracle
        addr: 0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE
        token_decimals: 18
      # DAI
      0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3: !Oracle
        addr: 0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE
        token_decimals: 18

    submit_rpcs:
      - !Normal https://bsc-dataseed1.bnbchain.org
      - !Private
        url: https://bsc.rpc.blxrbdn.com
        has_mev: true

    wrapped_native_token: 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
    railgun_contract: 0x590162bf4b50f6576a459b75309ee21d92178a10
    relay_adapt_contract: 0xf82d00fc51f730f42a00f85e74895a2849fff2dd
    multicall_contract: 0xcA11bde05977b3631167028862bE2a173976CA11

  # Polygon
  - chain_id: 137
    viewing_privkey: 0x82a57...
    evm_wallets:
      - 0xabcd1234...
    fee_bonus: 25
    fees_ttl: 5m
    fees_refresh_interval: 30s
    identifier: rust-broadcaster
    query_rpcs:
      - https://polygon-public.nodies.app
    fees:
      # WMATIC
      0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270: !Fixed "1ether"
      # USDT
      0xc2132d05d31c914a87c6611c10748aeb04b58e8f: !Oracle
        addr: 0xAB594600376Ec9fD91F8e885dADF0CE036862dE0
        token_decimals: 6
      # USDC
      0x2791bca1f2de4661ed88a30c99a7a9449aa84174: !Oracle
        addr: 0xAB594600376Ec9fD91F8e885dADF0CE036862dE0
        token_decimals: 6
      # DAI
      0x8f3cf7ad23cd3cadbd9735aff958023239c6a063: !Oracle
        addr: 0xAB594600376Ec9fD91F8e885dADF0CE036862dE0
        token_decimals: 18

    submit_rpcs:
      - !Normal https://poly.api.pocket.network
      - !Normal https://polygon-public.nodies.app
      - !Normal https://api.zan.top/polygon-mainnet
    wrapped_native_token: 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
    railgun_contract: 0x19b620929f97b7b990801496c3b361ca5def8c71
    relay_adapt_contract: 0xF82d00fC51F730F42A00F85E74895a2849ffF2Dd
    multicall_contract: 0xcA11bde05977b3631167028862bE2a173976CA11

  # Arbitrum
  - chain_id: 42161
    viewing_privkey: 0x82a57...
    evm_wallets:
      - 0xabcd1234...
    fee_bonus: 25
    fees_ttl: 5m
    fees_refresh_interval: 30s
    identifier: rust-broadcaster
    query_rpcs:
      - https://arb1.arbitrum.io/rpc
    fees:
      # WETH
      0x82af49447d8a07e3bd95bd0d56f35241523fbab1: !Fixed "1ether"
      # USDT
      0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9: !Oracle
        addr: 0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612
        token_decimals: 6
      # USDC.e
      0xff970a61a04b1ca14834a43f5de4533ebddb5cc8: !Oracle
        addr: 0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612
        token_decimals: 6
      # USDC
      0xaf88d065e77c8cc2239327c5edb3a432268e5831: !Oracle
        addr: 0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612
        token_decimals: 18
      # DAI
      0xda10009cbd5d07dd0cecc66161fc93d7c9000da1: !Oracle
        addr: 0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612
        token_decimals: 18
      # WBTC
      0x912ce59144191c1204e64559fe8253a0e49e6548: !Oracle
        addr: 0xc5a90A6d7e4Af242dA238FFe279e9f2BA0c64B2e
        is_inversed: true
        token_decimals: 8

    submit_rpcs:
      - !Normal https://arb1.arbitrum.io/rpc
    wrapped_native_token: 0x82af49447d8a07e3bd95bd0d56f35241523fbab1
    railgun_contract: 0xfa7093cdd9ee6932b4eb2c9e1cde7ce00b1fa4b9
    relay_adapt_contract: 0xB4F2d77bD12c6b548Ae398244d7FAD4ABCE4D89b
    multicall_contract: 0xcA11bde05977b3631167028862bE2a173976CA11


# Optional override for local db root.
#db_dir: ./db

# Optional admin API for online wallet resets.
#admin:
#  listen_addr: 127.0.0.1:3001
#  token: "change-me"

waku:
  # URL to a dedicated nwaku relay (optional)
  #nwaku_url: <FILL_ME>

  # Waku cluster id
  cluster_id: 1

  # List of custom DNS-based enr trees to bootstrap the libp2p network.
  #  Leave commented out to use default bootstrap nodes.
  #  Use empty list to disable DNS bootstrap.
  #dns_enr_trees: []

  # DNS-over-HTTPS endpoint to use for DNS resolution.
  doh_endpoint: "https://cloudflare-dns.com/dns-query"

  # Maximum number of peers to maintain persistent connections with
  max_peers: 10

  # Timeout for establishing a peer connection
  peer_connection_timeout: "10s"

  # List of direct peers to connect to. More peers may be discovered through Peer Exchange protocol.
  direct_peers:
    - peer_id: "16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m"
      addrs: [ "/dns4/prod.rootedinprivacy.com/tcp/30304/p2p/16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m", "/dns4/prod.rootedinprivacy.com/tcp/8000/wss/p2p/16Uiu2HAkwNeQVY32bUrL1eM68ryMa48PXY5Bhfxfg9e2byYcc46m" ]

query_rpc_cooldown: 3m
poi_rpc: https://ppoi.fdi.network
required_poi_list:
  # Chainalysis OFAC Sanctions API
  - efc6ddb59c098a13fb2b618fdae94c1c3a807abc8fb1837c93620c9143ee9e88
